project_name: "Substation_HV_Panel"
calculation_mode: "AC"
frequency: 50
temperature: 70

source:
    type: "Vsource"
    basekv: 10.0 # Лінійна напруга 400В
    isc3: 10000 # Струм 3-фазного КЗ на шинах ТР
    pu: 1.05 # Уновень напряжения
    X1R1: 10.0 # Соотношение X/R
    neutral_grounding: "Isolated" # Глухозаземлена нейтраль (0.4 кВ)

topology:
    - name: "Main_Feeder"
      from_bus: "SourceBus"
      to_bus: "Distribution_Board"
      cable_id: "VVGng_2х50" # Обов'язково має бути в library.ods
      length_km: 1.200 # Довжина
      breaker_id: "C60H-DC_16A_2P_C" # Автомат захисту

    - name: "Lighting_Circuit 1"
      from_bus: "Distribution_Board"
      to_bus: "Light_Panel 1"
      cable_id: "VVGng_2х50"
      length_km: 1.300
      breaker_id: "C60H-DC_2A_2P_C"

    - name: "Lighting_Circuit 2"
      from_bus: "Distribution_Board"
      to_bus: "Light_Panel 2"
      cable_id: "VVGng_2х50"
      length_km: 2.500
      breaker_id: "C60H-DC_2A_2P_C"

load:
    - name: "L1 load"
      bus: "Light_Panel 1"
      power_kw: 100
      pf: 0.9

    - name: "L2 load"
      bus: "Light_Panel 2"
      power_kw: 50
      pf: 0.9
