project_name: "Substation_Alpha_DC"
calculation_mode: "DC"
voltage_kv: 0.22
temperature: 20 # Робоча температура для розрахунку КЗ

battery:
    name: "BAT1"
    bus: "B1 Bat"
    model_id: "BAE_10_OGi_250"
    n_cells: 104
    jumpers_mohm: 10.5 #103 * 25.0 mm² 150.0 mm перемычки

topology:
    # Описуємо послідовні ділянки мережі
    - name: "W1"
      from_bus: "B1 Bat"
      to_bus: "B2 ShPT"
      cable_id: "VVGng_2x70"
      length_km: 0.03
      fuse_id: "PNA000_125A_2P"

    - name: "W2"
      from_bus: "B2 ShPT"
      to_bus: "B3 Pan. RZA"
      cable_id: "VVGng_2x4"
      length_km: 0.04
      fuse_id: "PNA000_20A_2P"

    - name: "W3"
      from_bus: "B3 Pan. RZA"
      to_bus: "B4 VRP 110"
      cable_id: "VVGng_2х2.5"
      length_km: 0.15
      breaker_id: "C60H-DC_2A_2P_C"

    - name: "W4"
      from_bus: "B2 ShPT"
      to_bus: "B5 Pan. KRUE"
      cable_id: "VVGng_2x10"
      length_km: 0.07
      fuse_id: "PNA000_40A_2P"

    - name: "W5"
      from_bus: "B5 Pan. KRUE"
      to_bus: "B6 Priv. KRUE"
      cable_id: "VVGng_2х1.5"
      length_km: 0.015
      breaker_id: "C60H-DC_10A_2P_C"

    - name: "W6"
      from_bus: "B2 ShPT"
      to_bus: "B7 ASU TP"
      cable_id: "VVGng_2х2.5"
      length_km: 0.02
      fuse_id: "PNA000_25A_2P"

load:
    - name: "Sum. Pan. RZA"
      bus: "B3 Pan. RZA"
      power_kw: 2.728

    - name: "VRP 110 Privod"
      bus: "B4 VRP 110"
      power_kw: 0.022

    - name: "Sum. Pan. KRUE"
      bus: "B5 Pan. KRUE"
      power_kw: 5.06

    - name: "Priv. KRUE"
      bus: "B6 Priv. KRUE"
      power_kw: 0.88

    - name: "ASU TP"
      bus: "B7 ASU TP"
      power_kw: 0.55
